### ISSUE TITLE
Fetch manifests is failing

### ISSUE THREAD

**Issue by aganders3** [napari/npe2api#20]
It looks like it's been failing for a couple weeks.

I think it's consistently failing when trying to commit the changes back to the repo - 403 error so maybe just an expired token or something?
```
remote: Permission to napari/npe2api.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/napari/npe2api/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by aganders3** [comment]
It might just need this added to the workflow? I'm not sure why it was working two weeks ago though:

```
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
```

**Comment by Czaki** [comment]
> It might just need this added to the workflow? I'm not sure why it was working two weeks ago though:

2 weeks ago multiple workflows (in napari organisation) starts failing because lack of permissions,
